name: MB
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26128
title: Matthew Blakemore
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2c6b1'
    - '#3a292d'
    - '#645e67'
    - '#a4232a'
    - '#f2faff'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
