name: MB
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9347036588005722
title: Matthew Blakemore
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#97080f'
    - '#800000'
    - '#000000'
    - '#ff0000'
    - '#550000'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
